### ISSUE TITLE
Tests depends on OS configuration

### ISSUE THREAD

**Issue by maxkatz6** [asklar/XamlTreeDump#2]
Some tests fall on my machine. After debug I see clear reason for that:
```
string:Expected #FF000000 got #FFFFFFFF
Property Foreground compared differently String String: expected "#FF000000" got "#FFFFFFFF"
in key array element
Array element 0 expected Object got Object
in key children
Property children compared differently Array Array: expected [{"XamlType":"Windows.UI.Xaml.Controls.CheckBox","Background":null,"BorderBrush":null,"BorderThickness":"0,0,0,0","Clip":null,"CornerRadius":"0,0,0,0","FlowDirection":"LeftToRight","Foreground":"#FF000000","HorizontalAlignment":"Stretch","Margin":"0,0,0,0","Padding":"0,0,0,0","RenderSize":[0,0],"VerticalAlignment":"Stretch"}] got [{"XamlType":"Windows.UI.Xaml.Controls.CheckBox","Background":null,"BorderBrush":null,"BorderThickness":"0,0,0,0","Clip":null,"CornerRadius":"0,0,0,0","FlowDirection":"LeftToRight","Foreground":"#FFFFFFFF","HorizontalAlignment":"Stretch","Margin":"0,0,0,0","Padding":"0,0,0,0","RenderSize":[0,0],"VerticalAlignment":"Stretch"}]
in key root
```

It occurs, when I use Dark theme for Windows. But tests expect foreground from Light theme.
Every tests passes after I change theme to Light and target project instead of nuget package.

**Comment by maxkatz6** [comment]
It seems I can't change App.RequestedTheme on Test application to fix it.

**Comment by asklar** [comment]
thanks for filing @maxkatz6 - it looks like setting RequestedTheme in markup doesn't quite work (at least in unit tests?), I filed https://github.com/microsoft/microsoft-ui-xaml/issues/2666 so that we can take a look at it.
For the time being, I set it programmatically in the test's `OnLaunched` and it works now, let me know if you are still running into issues.
